# Generated by Django 3.2.6 on 2021-09-08 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_path', models.URLField()),
                ('shortened_url', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(5)])),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
