# Generated by Django 3.2.6 on 2021-09-08 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0003_alter_urllead_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllead',
            name='shortened_url',
            field=models.SlugField(default='622DBB', unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
