# Generated by Django 3.2.6 on 2021-09-08 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0006_auto_20210908_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllead',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urllead',
            name='shortened_url',
            field=models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
