# Generated by Django 3.2.6 on 2021-09-10 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0007_auto_20210908_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllead',
            name='shortened_url',
            field=models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
