# Generated by Django 3.2.6 on 2021-09-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0008_alter_urllead_shortened_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllead',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
