# Generated by Django 3.2.6 on 2021-09-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0009_urllead_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urllead',
            old_name='created_date',
            new_name='last_modified',
        ),
    ]
