# Generated by Django 3.2.7 on 2021-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0011_imagestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
